# - A Job creates one or more Pods and ensures that a specified number of them successfully terminate. As pods successfully complete, the Job tracks the successful completions. When a specified number of successful completions is reached, the task (i.e., Job) is complete. Deleting a Job will clean up the Pods it created. Jobs are useful for batch processing tasks, such as data processing, backups, or any task that needs to run to completion rather than continuously.
apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: nginx

spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:
      containers:
        - name: batch-container
          image: busybox:latest
          command: ["sh", "-c", "echo Hello, Kubernetes Job! && sleep 10"]
      restartPolicy: Never
