kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: apache-vpa
  namespace: apache

spec:
  targetRef:
    apiVersion: app/v1
    kind: Deployment
    name: apache-deployment
  
  updatePolicy:
    updateMode: "Auto"